import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

export default function LeaseNew({ session }) {
  const navigate = useNavigate()
  const [properties, setProperties] = useState([])
  const [tenants, setTenants] = useState([])
  const [loading, setLoading] = useState(false)
  const [form, setForm] = useState({
    property_id: '',
    tenant_id: '',
    start_date: '',
    end_date: '',
    rent_amount: '',
    security_deposit: '',
  })

  useEffect(() => { fetchData() }, [])

  async function fetchData() {
    const uid = session.user.id
    const [p, t] = await Promise.all([
      supabase.from('properties').select('*').eq('landlord_id', uid),
      supabase.from('tenants').select('*').eq('landlord_id', uid),
    ])
    setProperties(p.data || [])
    setTenants(t.data || [])
  }

  async function generatePDF(leaseData) {
    const pdfDoc = await PDFDocument.create()
    const page = pdfDoc.addPage([612, 792])
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
    const { height } = page.getSize()

    const draw = (text, x, y, size = 11, bold = false) => {
      page.drawText(text, { x, y, size, font: bold ? boldFont : font, color: rgb(0, 0, 0) })
    }

    draw('RESIDENTIAL LEASE AGREEMENT', 150, height - 60, 16, true)
draw('--------------------------------------------------', 50, height - 80, 10)
draw('PROPERTY', 50, height - 110, 11, true)
draw(`Address: ${leaseData.address}`, 50, height - 130)
draw(`City: ${leaseData.city}, CA ${leaseData.zip}`, 50, height - 148)
draw('TENANT', 50, height - 178, 11, true)
draw(`Name: ${leaseData.tenant_name}`, 50, height - 198)
draw(`Email: ${leaseData.tenant_email}`, 50, height - 216)
draw(`Phone: ${leaseData.tenant_phone}`, 50, height - 234)
draw('LEASE TERMS', 50, height - 264, 11, true)
draw(`Start Date: ${leaseData.start_date}`, 50, height - 284)
draw(`End Date: ${leaseData.end_date}`, 50, height - 302)
draw(`Monthly Rent: $${leaseData.rent_amount}`, 50, height - 320)
draw(`Security Deposit: $${leaseData.security_deposit}`, 50, height - 338)
draw('TERMS AND CONDITIONS', 50, height - 368, 11, true)
const terms = [
  '1. Rent is due on the 1st of each month.',
  '2. Late fee of $50 applies after the 5th of the month.',
  '3. Tenant is responsible for utilities unless otherwise agreed.',
  '4. No pets without written landlord approval.',
  '5. Tenant must give 30 days written notice before vacating.',
  '6. Landlord must give 24 hours notice before entry.',
  '7. Property must be returned in same condition as received.',
]
terms.forEach((term, i) => draw(term, 50, height - 390 - i * 18, 10))
draw('--------------------------------------------------', 50, height - 530, 10)
draw('SIGNATURES', 50, height - 550, 11, true)
draw('Landlord: ______________________________', 50, height - 580)
draw('Date: _______________', 350, height - 580)
draw('Tenant: ______________________________', 50, height - 620)
draw('Date: _______________', 350, height - 620)
draw('Generated by Renty -- rentyapp.net', 180, 30, 9)
    const pdfBytes = await pdfDoc.save()
    return pdfBytes
  }

 async function handleSubmit(e) {
  e.preventDefault()
  setLoading(true)

  try {
    const property = properties.find(p => p.id === form.property_id)
    const tenant = tenants.find(t => t.id === form.tenant_id)

    const leaseData = {
      address: property.address,
      city: property.city || '',
      zip: property.zip || '',
      tenant_name: tenant.full_name,
      tenant_email: tenant.email || '',
      tenant_phone: tenant.phone || '',
      start_date: form.start_date,
      end_date: form.end_date,
      rent_amount: form.rent_amount,
      security_deposit: form.security_deposit || '0',
    }

    const pdfBytes = await generatePDF(leaseData)

    const fileName = `${session.user.id}/lease-${Date.now()}.pdf`

    const { error: uploadError } = await supabase.storage
      .from('leases')
      .upload(fileName, pdfBytes, {
        contentType: 'application/pdf',
        upsert: true
      })

    if (uploadError) {
      alert('Upload failed: ' + uploadError.message)
      setLoading(false)
      return
    }

    const { data: urlData } = supabase.storage
      .from('leases')
      .getPublicUrl(fileName)

    const { data: lease, error: leaseError } = await supabase
      .from('leases')
      .insert({
        property_id: form.property_id,
        tenant_id: form.tenant_id,
        start_date: form.start_date,
        end_date: form.end_date,
        rent_amount: form.rent_amount,
        security_deposit: form.security_deposit,
        landlord_id: session.user.id,
        pdf_url: urlData.publicUrl,
        status: 'draft',
      })
      .select()
      .single()

    if (leaseError) {
      alert('Lease save failed: ' + leaseError.message)
      setLoading(false)
      return
    }

    setLoading(false)
    navigate(`/leases/${lease.id}`)

  } catch (err) {
    alert('Error: ' + err.message)
    setLoading(false)
  }
}

  const inputStyle = {
    padding: '0.75rem',
    borderRadius: '6px',
    border: '1px solid #ccc',
    fontSize: '1rem',
    width: '100%',
  }

  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', maxWidth: '700px', margin: '0 auto', padding: '2rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <h2>New Lease</h2>
        <button onClick={() => navigate('/dashboard')} style={{ padding: '0.5rem 1rem', cursor: 'pointer', background: 'none', border: '1px solid #ccc', borderRadius: '6px' }}>← Dashboard</button>
      </div>

      <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        <div>
          <label style={{ display: 'block', marginBottom: '0.4rem', fontWeight: '500' }}>Property</label>
          <select value={form.property_id} onChange={e => setForm({ ...form, property_id: e.target.value })} required style={inputStyle}>
            <option value="">Select a property</option>
            {properties.map(p => (
              <option key={p.id} value={p.id}>{p.address}, {p.city}</option>
            ))}
          </select>
        </div>

        <div>
          <label style={{ display: 'block', marginBottom: '0.4rem', fontWeight: '500' }}>Tenant</label>
          <select value={form.tenant_id} onChange={e => setForm({ ...form, tenant_id: e.target.value })} required style={inputStyle}>
            <option value="">Select a tenant</option>
            {tenants.map(t => (
              <option key={t.id} value={t.id}>{t.full_name}</option>
            ))}
          </select>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
          <div>
            <label style={{ display: 'block', marginBottom: '0.4rem', fontWeight: '500' }}>Start Date</label>
            <input type="date" value={form.start_date} onChange={e => setForm({ ...form, start_date: e.target.value })} required style={inputStyle} />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: '0.4rem', fontWeight: '500' }}>End Date</label>
            <input type="date" value={form.end_date} onChange={e => setForm({ ...form, end_date: e.target.value })} required style={inputStyle} />
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
          <div>
            <label style={{ display: 'block', marginBottom: '0.4rem', fontWeight: '500' }}>Monthly Rent ($)</label>
            <input type="number" value={form.rent_amount} onChange={e => setForm({ ...form, rent_amount: e.target.value })} required style={inputStyle} />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: '0.4rem', fontWeight: '500' }}>Security Deposit ($)</label>
            <input type="number" value={form.security_deposit} onChange={e => setForm({ ...form, security_deposit: e.target.value })} style={inputStyle} />
          </div>
        </div>

        <button type="submit" disabled={loading} style={{ padding: '1rem', background: '#000', color: '#fff', border: 'none', borderRadius: '8px', cursor: 'pointer', fontSize: '1rem', marginTop: '1rem' }}>
          {loading ? 'Generating PDF...' : 'Generate Lease PDF'}
        </button>
      </form>
    </div>
  )
}
