import { useNavigate } from 'react-router-dom'

export default function Terms() {
  const navigate = useNavigate()
  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', maxWidth: '800px', margin: '0 auto', padding: '2rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <h1 style={{ margin: 0, fontSize: '1.5rem', cursor: 'pointer' }} onClick={() => navigate('/')}>Renty</h1>
        <button onClick={() => navigate('/')} style={{ padding: '0.5rem 1rem', cursor: 'pointer', background: 'none', border: '1px solid #ccc', borderRadius: '6px' }}>← Back</button>
      </div>

      <h2>Terms of Service</h2>
      <p style={{ color: '#666' }}>Last updated: June 2, 2026</p>

      <div style={{ lineHeight: '1.8', color: '#333' }}>
        <h3>1. Acceptance of Terms</h3>
        <p>By using Renty, you agree to these Terms of Service. If you do not agree, do not use the service.</p>

        <h3>2. Description of Service</h3>
        <p>Renty provides landlord management software including lease agreement generation, tenant management, and property tracking. Renty is a tool to assist landlords — it does not provide legal advice.</p>

        <h3>3. Lease Agreements</h3>
        <p>Lease agreements generated by Renty are provided as templates for convenience. Renty does not guarantee that generated leases comply with all local, state, or federal laws. You are responsible for ensuring your lease agreements are legally compliant in your jurisdiction. We strongly recommend having an attorney review your leases.</p>

        <h3>4. Subscription and Payment</h3>
        <p>Renty Pro is $9/month with a 7-day free trial. You may cancel at any time. Cancellations take effect at the end of the current billing period. No refunds are provided for partial months.</p>

        <h3>5. Acceptable Use</h3>
        <p>You agree to use Renty only for lawful property management purposes. You may not use Renty to discriminate against tenants based on protected characteristics under the Fair Housing Act.</p>

        <h3>6. Data Responsibility</h3>
        <p>You are responsible for the accuracy of information you enter into Renty. You are responsible for maintaining appropriate consent from tenants whose data you enter.</p>

        <h3>7. Limitation of Liability</h3>
        <p>Renty is provided "as is" without warranties of any kind. Renty shall not be liable for any damages arising from your use of the service, including but not limited to lease disputes, tenant issues, or data loss.</p>

        <h3>8. Termination</h3>
        <p>We reserve the right to terminate accounts that violate these terms. You may terminate your account at any time by contacting support@rentyapp.net.</p>

        <h3>9. Changes to Terms</h3>
        <p>We may update these terms at any time. Continued use of Renty after changes constitutes acceptance of the new terms.</p>

        <h3>10. Contact</h3>
        <p>For questions about these terms, contact us at <a href="mailto:support@rentyapp.net">support@rentyapp.net</a>.</p>
      </div>
    </div>
  )
}
